<a href="https://colab.research.google.com/github/Nilufayeasmin299/Phishig-detection-using-both-machine-learning-and-deep-learning-techniques/blob/main/Phishing_detection_using_ML_after_feature_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
#importing all necessary packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from xgboost import XGBClassifier

In [ ]:
#load dataset
df=pd.read_csv('/content/gdrive/MyDrive/Second paper/Dataset/New_data')
df.head()

Unnamed: 0  having_At_Symbol  ...  Links_pointing_to_page  Result
0           0                 1  ...                       1      -1
1           1                 1  ...                       1      -1
2           2                 1  ...                       0      -1
3           3                 1  ...                      -1      -1
4           4                 1  ...                       1       1

[5 rows x 17 columns]

In [ ]:
df.columns

Index(['Unnamed: 0', 'having_At_Symbol', 'Prefix_Suffix', 'having_Sub_Domain',
       'SSLfinal_State', 'Domain_registeration_length', 'HTTPS_token',
       'Request_URL', 'URL_of_Anchor', 'Links_in_tags', 'SFH', 'on_mouseover',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Links_pointing_to_page',
       'Result'],
      dtype='object')

In [ ]:
data=df.drop(['Unnamed: 0'], axis=1)

In [ ]:
data.head()

having_At_Symbol  Prefix_Suffix  ...  Links_pointing_to_page  Result
0                 1             -1  ...                       1      -1
1                 1             -1  ...                       1      -1
2                 1             -1  ...                       0      -1
3                 1             -1  ...                      -1      -1
4                 1             -1  ...                       1       1

[5 rows x 16 columns]

In [ ]:
data.columns

Index(['having_At_Symbol', 'Prefix_Suffix', 'having_Sub_Domain',
       'SSLfinal_State', 'Domain_registeration_length', 'HTTPS_token',
       'Request_URL', 'URL_of_Anchor', 'Links_in_tags', 'SFH', 'on_mouseover',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Links_pointing_to_page',
       'Result'],
      dtype='object')

In [ ]:
data.shape

(11055, 16)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   having_At_Symbol             11055 non-null  int64
 1   Prefix_Suffix                11055 non-null  int64
 2   having_Sub_Domain            11055 non-null  int64
 3   SSLfinal_State               11055 non-null  int64
 4   Domain_registeration_length  11055 non-null  int64
 5   HTTPS_token                  11055 non-null  int64
 6   Request_URL                  11055 non-null  int64
 7   URL_of_Anchor                11055 non-null  int64
 8   Links_in_tags                11055 non-null  int64
 9   SFH                          11055 non-null  int64
 10  on_mouseover                 11055 non-null  int64
 11  age_of_domain                11055 non-null  int64
 12  DNSRecord                    11055 non-null  int64
 13  web_traffic                  11055 non-null  i

In [ ]:
df['Result'].value_counts()

 1    6157
-1    4898
Name: Result, dtype: int64

In [ ]:
y=df['Result']
X=df.drop('Result',axis=1)

In [ ]:
X.shape, y.shape

((11055, 16), (11055,))

In [ ]:
# Splitting the dataset into train and test sets: 80-20 split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 12)
X_train.shape, X_test.shape

((8844, 16), (2211, 16))

#**Decision tree Classifier**

In [ ]:

classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 925   76]
 [  52 1158]]
              precision    recall  f1-score   support

          -1       0.95      0.92      0.94      1001
           1       0.94      0.96      0.95      1210

    accuracy                           0.94      2211
   macro avg       0.94      0.94      0.94      2211
weighted avg       0.94      0.94      0.94      2211



In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.942107643600181


#**Random Forest Classifier**

In [ ]:
forest = RandomForestClassifier(max_depth=5)
# fit the model 
forest.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred=forest.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 909   92]
 [  52 1158]]
              precision    recall  f1-score   support

          -1       0.95      0.91      0.93      1001
           1       0.93      0.96      0.94      1210

    accuracy                           0.93      2211
   macro avg       0.94      0.93      0.93      2211
weighted avg       0.94      0.93      0.93      2211



In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.9348710990502035


#**XGBoost classifier**

In [ ]:
xgb = XGBClassifier(learning_rate=0.4,max_depth=7)
#fit the model
xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.4, max_delta_step=0, max_depth=7,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
y_pred=xgb.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 955   46]
 [  46 1164]]
              precision    recall  f1-score   support

          -1       0.95      0.95      0.95      1001
           1       0.96      0.96      0.96      1210

    accuracy                           0.96      2211
   macro avg       0.96      0.96      0.96      2211
weighted avg       0.96      0.96      0.96      2211



In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.95838986883763


#**Support Vector Machine**

In [ ]:
svm = SVC(kernel='linear', C=1.0, random_state=12)
#fit the model
svm.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=12, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
y_pred=svm.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 901  100]
 [  64 1146]]
              precision    recall  f1-score   support

          -1       0.93      0.90      0.92      1001
           1       0.92      0.95      0.93      1210

    accuracy                           0.93      2211
   macro avg       0.93      0.92      0.92      2211
weighted avg       0.93      0.93      0.93      2211



In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.9258254183627318


#**K-nearest neighbours**

In [ ]:
knn=KNeighborsClassifier()
#fit the model
knn.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred=knn.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[504 497]
 [375 835]]
              precision    recall  f1-score   support

          -1       0.57      0.50      0.54      1001
           1       0.63      0.69      0.66      1210

    accuracy                           0.61      2211
   macro avg       0.60      0.60      0.60      2211
weighted avg       0.60      0.61      0.60      2211



In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.6056083220262325


#**Gaussian Naive-Bayes**

In [ ]:
gnb=GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred=gnb.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 954   47]
 [ 173 1037]]
              precision    recall  f1-score   support

          -1       0.85      0.95      0.90      1001
           1       0.96      0.86      0.90      1210

    accuracy                           0.90      2211
   macro avg       0.90      0.91      0.90      2211
weighted avg       0.91      0.90      0.90      2211



In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.900497512437811
